version: '3'
services:
    sonar:
        build: ./sonar
        depends_on:
            - api
            - ui
            - proxy
    api:
        build:
          context: ./api
        volumes:
            - ./api/app:/usr/local/src/skiff/app/api/app
            - ./api/core:/usr/local/src/skiff/app/api/core
            - ./api/db:/usr/local/src/skiff/app/api/db
            - ./api/models:/usr/local/src/skiff/app/api/models
            - ./api/routers:/usr/local/src/skiff/app/api/routers
            - ./api/services:/usr/local/src/skiff/app/api/services
            - ./api/utils:/usr/local/src/skiff/app/api/utils
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=DEBUG
        command: ["main:app", "--host", "0.0.0.0", "--reload"]
        depends_on:
            - mongodb
    ui:
        build:
          context: ./ui
          dockerfile: Dockerfile-local
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ./ui/src:/usr/local/src/skiff/app/ui/src
            - ./ui/public:/usr/local/src/skiff/app/ui/public
            - ./ui/package.json:/usr/local/src/skiff/app/ui/package.json
            - ./ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json
            - ./ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=devusername
            - MONGO_INITDB_ROOT_PASSWORD=devpassword
        volumes:
            - ./database/data:/data/db
        ports:
            - 27017:27017
    proxy:
        build: ./proxy
        ports:
            - 8080:80
        depends_on:
            - api
            - ui

    # This service is optional!
    # It is not used during deployment, but simply runs a grobid service
    # which the CLI can use for pre-processing PDFs, using grobid to provide
    # the detailed token information.
    grobid:
        image: 'allenai/grobid:0.5.6-pdf-structure'
        ports:
            - '8070:8070'
            - '8071:8071'
